-- CreateEnum
CREATE TYPE "EuAIActEntityType" AS ENUM ('PROVIDER', 'DEPLOYER', 'DISTRIBUTOR', 'IMPORTER', 'PRODUCT_MANUFACTURER', 'AUTHORISED_REPRESENTATIVE');

-- AlterTable
ALTER TABLE "AIAsset" ADD COLUMN     "euEntityType" "EuAIActEntityType";
